import { expect, test } from '@playwright/test';
import { loadFixtureWithBundle } from './support.js';

declare global {
  interface Window {
    SelectorEngine: typeof import('../src/index.js');
  }
}

test.beforeEach(async ({ page }) => {
  await loadFixtureWithBundle(page, '/static.html');
});

test('a stable id produces the top-ranked id-strategy candidate', async ({ page }) => {
  const candidates = await page.evaluate(() => {
    const el = document.getElementById('headline')!;
    return window.SelectorEngine.generateSelectorCandidates(el);
  });
  expect(candidates[0]).toMatchObject({ selector: '#headline', strategy: 'id', matchCount: 1 });
});

test('a stable data-testid attribute is used when there is no id', async ({ page }) => {
  const candidates = await page.evaluate(() => {
    const el = document.querySelector('[data-testid="price"]')!;
    return window.SelectorEngine.generateSelectorCandidates(el);
  });
  expect(candidates[0]?.strategy).toBe('data-attr');
  expect(candidates[0]?.matchCount).toBe(1);
});

test('a repeating list item yields a shared tag+class candidate matching all siblings', async ({
  page,
}) => {
  const candidates = await page.evaluate(() => {
    const el = document.querySelector('#item-list .item')!;
    return window.SelectorEngine.generateSelectorCandidates(el);
  });
  const tagClass = candidates.find((c) => c.strategy === 'tag-class');
  expect(tagClass).toBeTruthy();
  expect(tagClass?.matchCount).toBe(3);
});

test('an autogenerated-looking id/class is excluded from id and tag-class strategies', async ({
  page,
}) => {
  const candidates = await page.evaluate(() => {
    const el = document.getElementById('ember482')!;
    return window.SelectorEngine.generateSelectorCandidates(el);
  });
  expect(candidates.some((c) => c.strategy === 'id')).toBe(false);
  expect(candidates.some((c) => c.strategy === 'tag-class')).toBe(false);
  // A fallback (parent-child or nth-of-type) must still be produced so the
  // element remains selectable, just ranked lower.
  expect(candidates.length).toBeGreaterThan(0);
  expect(candidates[0]?.score).toBeLessThan(60);
});

test('every returned candidate is verified to actually match the target element', async ({
  page,
}) => {
  const result = await page.evaluate(() => {
    const el = document.getElementById('product-link')!;
    const candidates = window.SelectorEngine.generateSelectorCandidates(el);
    return candidates.every((c) => Array.from(document.querySelectorAll(c.selector)).includes(el));
  });
  expect(result).toBe(true);
});
