import { expect, test } from '@playwright/test';
import { DEFAULT_NORMALIZATION_CONFIG, type Selection } from '@web-monitor/shared';
import { extractSelection } from '../src/extract.js';
import { RunnerCheckError } from '../src/errors.js';

function buildSelection(overrides: Partial<Selection>): Selection {
  return {
    id: 'sel-1',
    monitorId: 'mon-1',
    label: 'テスト項目',
    selectorType: 'css',
    selector: '',
    selectorCandidates: [],
    extractionMode: 'text',
    attributeName: null,
    normalization: DEFAULT_NORMALIZATION_CONFIG,
    matchMode: 'normalized',
    orderIndex: 0,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
    ...overrides,
  };
}

test.describe('extraction against the static fixture page', () => {
  test('extracts normalized text', async ({ page }) => {
    await page.goto('/static.html');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#headline', extractionMode: 'text' }),
    );
    expect(value.displayValue).toBe('初期の見出しです');
  });

  test('extracts an attribute value', async ({ page }) => {
    await page.goto('/static.html');
    const value = await extractSelection(
      page,
      buildSelection({
        selector: '#hero-image',
        extractionMode: 'attribute',
        attributeName: 'alt',
      }),
    );
    expect(value.displayValue).toBe('ヒーロー画像');
  });

  test('resolves link hrefs to absolute URLs', async ({ page }) => {
    await page.goto('/static.html');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#product-link', extractionMode: 'link' }),
    );
    expect(value.displayValue).toBe('http://localhost:4173/product');
  });

  test('resolves image src to an absolute URL', async ({ page }) => {
    await page.goto('/static.html');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#hero-image', extractionMode: 'image' }),
    );
    expect(value.displayValue).toBe('http://localhost:4173/images/hero.jpg');
  });

  test('extracts a repeating list in order', async ({ page }) => {
    await page.goto('/static.html');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#item-list .item', extractionMode: 'list' }),
    );
    expect(value.displayValue).toEqual(['項目A', '項目B', '項目C']);
  });

  test('extracts the whole document for the document selector type', async ({ page }) => {
    await page.goto('/static.html');
    const value = await extractSelection(
      page,
      buildSelection({ selectorType: 'document', selector: '', extractionMode: 'text' }),
    );
    expect(typeof value.displayValue).toBe('string');
    expect(value.displayValue as string).toContain('初期の見出しです');
  });

  test('raises SELECTOR_NOT_FOUND when nothing matches', async ({ page }) => {
    await page.goto('/static.html');
    await expect(
      extractSelection(
        page,
        buildSelection({ selector: '#does-not-exist', extractionMode: 'text' }),
      ),
    ).rejects.toMatchObject({
      statusCode: 'SELECTOR_NOT_FOUND',
    } satisfies Partial<RunnerCheckError>);
  });

  test('raises SELECTOR_NOT_UNIQUE for a non-list selector matching multiple elements', async ({
    page,
  }) => {
    await page.goto('/static.html');
    await expect(
      extractSelection(page, buildSelection({ selector: '.item', extractionMode: 'text' })),
    ).rejects.toMatchObject({
      statusCode: 'SELECTOR_NOT_UNIQUE',
    } satisfies Partial<RunnerCheckError>);
  });

  test('does not treat an autogenerated-looking id/class element as stable content by itself', async ({
    page,
  }) => {
    await page.goto('/static.html');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#ember482', extractionMode: 'text' }),
    );
    expect(value.displayValue).toContain('自動生成');
  });
});

test.describe('extraction against the dynamic fixture page', () => {
  test('waits for client-side rendered content to appear', async ({ page }) => {
    await page.goto('/dynamic.html');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#headline', extractionMode: 'text' }),
    );
    expect(value.displayValue).toBe('動的に生成された見出しです');
  });

  test('reflects the changed variant once rendered', async ({ page }) => {
    await page.goto('/dynamic.html?variant=changed');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#headline', extractionMode: 'text' }),
    );
    expect(value.displayValue).toBe('動的に更新された見出しです');
  });

  test('extracts a dynamically rendered list', async ({ page }) => {
    await page.goto('/dynamic.html');
    const value = await extractSelection(
      page,
      buildSelection({ selector: '#item-list .item', extractionMode: 'list' }),
    );
    expect(value.displayValue).toEqual(['動的項目A', '動的項目B']);
  });
});
