import { describe, expect, it } from 'vitest';
import { isLikelyAutogenerated, isStableToken, scoreToken } from '../src/token-quality.js';

describe('scoreToken / isLikelyAutogenerated', () => {
  it('treats a UUID as autogenerated', () => {
    expect(isLikelyAutogenerated('3fa85f64-5717-4562-b3fc-2c963f66afa6')).toBe(true);
  });

  it('treats a long hex hash as autogenerated', () => {
    expect(isLikelyAutogenerated('a1b2c3d4e5f6')).toBe(true);
  });

  it('treats a long numeric-looking timestamp id as autogenerated', () => {
    expect(isLikelyAutogenerated('1717000000000')).toBe(true);
  });

  it('treats framework-scoped class names as autogenerated', () => {
    expect(isLikelyAutogenerated('css-1a2b3c')).toBe(true);
    expect(isLikelyAutogenerated('sc-bdVaJa')).toBe(true);
    expect(isLikelyAutogenerated('ember482')).toBe(true);
  });

  it('treats ordinary semantic ids and classes as stable', () => {
    expect(isStableToken('headline')).toBe(true);
    expect(isStableToken('product-price')).toBe(true);
    expect(isStableToken('main-navigation')).toBe(true);
  });

  it('scores empty tokens as unstable', () => {
    expect(scoreToken('')).toBe(0);
  });
});
