const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const LONG_HEX_PATTERN = /^[0-9a-f]{8,}$/i;
const LONG_NUMERIC_PATTERN = /^\d{6,}$/;
const FRAMEWORK_GENERATED_PATTERN =
  /^(css|sc|v|ember|mui|chakra|jsx|styled|emotion)-?[0-9a-z]{3,}$/i;
// A hyphen-delimited final segment of 6+ chars that mixes letters and at
// least one digit reads as a generated hash suffix (e.g. "button-a3f9c1"),
// unlike a plain compound word like "main-navigation".
const TRAILING_HASH_SUFFIX_PATTERN = /-([0-9a-z]{6,})$/i;

/**
 * Heuristic quality score for an id/class token, in [0, 1]. Low scores mark
 * tokens that look machine-generated (hashes, UUIDs, timestamps, framework
 * scoped-class suffixes) and change across reloads/builds, so they must not
 * become the backbone of a stable selector.
 */
export function scoreToken(token: string): number {
  if (token.length === 0) return 0;
  if (UUID_PATTERN.test(token)) return 0;
  if (LONG_HEX_PATTERN.test(token) && token.length >= 8) return 0;
  if (LONG_NUMERIC_PATTERN.test(token)) return 0;
  if (FRAMEWORK_GENERATED_PATTERN.test(token)) return 0.05;
  const trailingSuffix = TRAILING_HASH_SUFFIX_PATTERN.exec(token)?.[1];
  if (trailingSuffix && /\d/.test(trailingSuffix)) return 0.2;

  const digitRatio = (token.match(/\d/g)?.length ?? 0) / token.length;
  if (token.length >= 6 && digitRatio > 0.4) return 0.2;

  if (token.length > 40) return 0.3;

  return 1;
}

export function isLikelyAutogenerated(token: string): boolean {
  return scoreToken(token) < 0.5;
}

export function isStableToken(token: string, minScore = 0.5): boolean {
  return scoreToken(token) >= minScore;
}
